### ISSUE TITLE
cogs not appearing

### ISSUE THREAD

**Issue by Ray-MRQ** [javascripto/syxcogs#7]
your cogs do not have the __init__ py meaning they don't actually appear 
![image](https://user-images.githubusercontent.com/10146271/41527000-be4623de-72dd-11e8-9f1e-aa0a0608498d.png)

**Comment by OfficialAudite** [comment]
I don't actually see the problem here \/

![image](https://i.imgur.com/TrHOwM0.png)

**Comment by Ray-MRQ** [comment]
Oh, I see what's up, that's V2 you posted your repo link on a V3 list red#1398

**Comment by OfficialAudite** [comment]
Yeah @Ray-Killer I didn't knew that there was V3. Might convert them to V3, but Ship command or cog is for V2 and V3.
